sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xzj292339
  redis:
    host: localhost
    port: 6379
    database: 5
  wechat:
    appid: wx325ff0ede6500050
    secret: c69938e66a0e108fbecc58dd1fa9db6f

